spring.application.name=delipedidos
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=T19_Delipedidos;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YonZ/72709545
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect